
@startuml ims_white

' Adding comments: https://plantuml.com/commons

skinparam Shadowing true
skinparam DefaultFontColor White
skinparam BackgroundColor #Grey
skinparam DefaultTextAlignment center
allowmixing
' legend from: https://stackoverflow.com/questions/30999290/how-to-generate-a-legend-with-colors-in-plantuml
skinparam linetype ortho

legend top right
    | Colour | Assigned To |
    |<#DarkGoldenRod>| Storage|
    |<#DarkBlue>| Infra|
    |<#ForestGreen>| Application|
endlegend

'bolding text: https://plantuml.com/creole#:~:text=for%20bold%20text,colorName%5D%5D%3E%20for%20strike%20text
' single element colouring: https://forum.plantuml.net/2/how-to-change-the-color-of-an-individual-element
' all colours: https://plantuml-documentation.readthedocs.io/en/latest/formatting/color-names.html
' colours ref2.0: https://crashedmind.github.io/PlantUMLHitchhikersGuide/color/color.html

'Adding headings: https://plantuml.com/creole

rectangle Heading #SlateGrey [
=Inventory Management System
/'....
==== Requirements Diagram'/
]

rectangle CUSTOMER #SlateGrey{
    rectangle NIC #DarkRed
}

rectangle PROJECTS #SlateGrey{
    rectangle MyGov #Red 
    rectangle eTransport #DarkRed 
    rectangle NSP #Red 
}

rectangle DATACENTER #SlateGrey{
rectangle DC_Delhi #DarkRed
}
rectangle APPLICATION_ENVIRONMENTS #SlateGrey{
rectangle Vahan #Red
rectangle Checkpost #DarkRed
rectangle Sarathi #Red
}

rectangle SETUP_ENVIROMENT #SlateGrey{
rectangle Testing #Red
rectangle Staging #DarkRed
rectangle Pre_Production #Red
rectangle Production #Red
}

rectangle SERVER_INVENTORY {

rectangle application  #LightGrey{

        rectangle DATABASE_Backup #SlateGrey{
                    rectangle Database_Start #ForestGreen[
            =DATABASE BACKUP 
        ]
        
        rectangle LAST_BACKUP_DATE #ForestGreen[
            =LAST BACKUP DATE
            ----
            22/09/23
        ]

        rectangle BACKUP_CONFIG #ForestGreen[
            =BACKUP CONFIG
            ----
            https://gitlab.com/checkpostApp1/backupconfig
        ]

        rectangle BACKUP  #ForestGreen[
            =BACKUP
            ----
            Yes
        ]

        rectangle DB_SERVER_READ_apps1  #ForestGreen[
            =DB SERVER READ
            ----
            10.246.40.182:5432
            10.242.36.129:5432
            10.242.36.130:5432
        ]

        rectangle DB_SERVER_WRITE_apps1  #ForestGreen[
            =DB SERVER WRITE
            ----
            10.246.40.186:5433
        ]

        rectangle DATABASE_apps1  #ForestGreen[
            =DATABASE NAME
            ----
            Postges
        ]
    }

    rectangle SERVICES #SlateGrey{
            rectangle Services_Start #ForestGreen[
            =SERVICES
        ]

        rectangle LISTENING_PORT_apps1  #ForestGreen[
            =LISTENING PORT
            ----
            25
        ]

        rectangle LISTENING_IP_apps1  #ForestGreen[
            =LISTENING IP
            ----
            127.0.0.1
        ]

        rectangle SERVICE_PATH_apps1  #ForestGreen[
            =SERVICE PATH
            ----
            /usr/libexec/postfix/master -w
            /opt/commvault/Base/cvd
            nimbus(controller)
            nimbus(spooler)
            /opt/commvault/Base/ClMgrS
            /usr/sbin/zabbix_agentd -c /etc/zabbix/zabbix_agentd.conf
            /opt/commvault/Base/cvd
            nimbus(hdb)
            nimbus(processes)
            nimbus(cdm)
            cam
            nimbus(logmon)
        ]

        rectangle SERVICE_NAME_apps1  #ForestGreen[
            =SERVICE NAME
            ----
            master
            cvd
            nimbus(control)
            nimbus(spoole)
            ClMgrS
            zabbix_agentd
            cvd
            nimbus(hdb)
            nimbus(process)
            nimbus(cdm)
            cam
            nimbus(logmon)
            ]
    }

    rectangle Tomcat_Details #SlateGrey{
        rectangle Tomcat_Start #ForestGreen[
            =TOMCAT DETAILS
        ]

        rectangle CONFIG_MAP_apps1  #ForestGreen[
            =CONFIG MAP
            ----
            server.XML
            https://gitlab.com/configmap/NA/-/blob/main/server.XML
            context.XML
            https://gitlab.com/configmap/NA/-/blob/main/Context.XML
            web.XML
            https://gitlab.com/configmap/NA/-/blob/main/web.xml
        ]

        rectangle WEBAPP_PATH_apps1  #ForestGreen[
            =WEBAPP PATH
            ----
            /u01/tcat_checkpost_8083/webapps
            /u01/tcat_checkpost_8084/webapps
            /u01/tcat_checkpost_8085/webapps
        ]

        rectangle LOGS_PATH_apps1  #ForestGreen[
            =LOGS PATH
            ----
            /u01/tcat_checkpost_8083/logs
            /u01/tcat_checkpost_8084/logs
            /u01/tcat_checkpost_8085/logs
        ]

        rectangle WAR_DEPLOYED_apps1  #ForestGreen[
            =WAR DEPLOYED
            ----
            CheckpostApp1.war
        ]


        rectangle TOMCAT_PORT_apps1  #ForestGreen[
            =TOMCAT PORT
            ----
            8083
            8084
            8085
        ]

        rectangle TOMCAT_NAME_apps1  #ForestGreen[
            =TOMCAT NAME
            ----
            tcat_checkpost_8083
            tcat_checkpost_8084
            tcat_checkpost_8085
        ]
    }

    rectangle network_details #SlateGrey{
          rectangle Network_Start #ForestGreen[
            =NETWORK DETAILS
        ]

        rectangle NTP_SERVER_apps1  #ForestGreen[
            =NTP SERVER
            ----
            Yes
        ]

        rectangle HAPROXY_PORT  #ForestGreen[
            =HAPROXY PORT
            ----
            80
        ]

        rectangle MAC_IP  #ForestGreen[
            =MAC IP
            ----
            00:00:5e:00:53:af
        ]

        rectangle LB_IP  #ForestGreen[
            =LB IP
            ----
            1.8
        ]

        /'rectangle IP  #ForestGreen[
            =IP
            ----
            10.249.221.21
        ]'/
    }

    rectangle App_Start #ForestGreen[
            =APP DETAILS
        ]

    rectangle App_Details #SlateGrey{
        
        /'rectangle HOSTNAME_apps1  #ForestGreen[
        =HOSTNAME
        ----
        Checkpost1
        ]'/

        rectangle DOCUMENT_TYPE_apps1  #ForestGreen[
            =DOCUMENT TYPE
            ----
            Automated
        ]
        rectangle DOCUMENT_PATH  #ForestGreen[
            =DEPLOYMENT DOCUMENT
            ----
            https://gitlab.com/checkpostApp1/Readme.md/
        ]

        rectangle DEPLOYMENT_DOCUMENT  #ForestGreen[
            =DEPLOYMENT DOCUMENT
            ----
            Yes
        ]

        rectangle GIT_REPOSITORY_LINK  #ForestGreen[
            =GIT REPOSITORY LINK
            ----
            https://gitlab.com/checkpostApp1
        ]

        rectangle GIT  #ForestGreen[
            =GIT ENVIRONMENT
            ----
            Yes
        ]

        rectangle APP_PLATFORM  #ForestGreen[
            =APP PLATFORM
            ----
            Systemd
        ]

        rectangle APP_DESCRIPTION #ForestGreen[
            =APP DESCRIPTION
            ----
            For vehicle tax collection
        ]

        rectangle PROGRAMMING_LANGUAGE_VERSION  #ForestGreen[
            =PROGRAMMING LANGUAGE VERSION
            ----
            1.8
        ]

        rectangle PROGRAMMING_LANGUAGE  #ForestGreen[
            =PROGRAMMING LANGUAGE
            ----
            Java
        ]

        rectangle API_Webservice_apps1  #ForestGreen[
            =API/WEBSERVICE URL
            ----
            CheckpostWebService
        ]

        rectangle APP_DEPLOYMENT_PREREQUISITES_apps1  #ForestGreen[
        =APP DEPLOYMENT PREREQUISITES
        =& DEPENDENCIES
        ----
        Java
        Tomcat
        CheckpostApp2
        ]

        rectangle LAST_APP_VERSION  #ForestGreen[
            =LAST APP VERSION
            ----
            22/09/23
        ]

        rectangle PUBLIC_URL  #ForestGreen[
            =PUBLIC URL
            ----
            checkpost.parivahan.gov.in/
        ]

        rectangle OWNER_CONTACT  #ForestGreen[
            =OWNER AND CONTACT DETAILS
            ----
            Mr. Avnish
            avnish@NIC.com
            9124233323
        ]

        rectangle APP_NAME  #ForestGreen[
            =APP
            ----
            CheckpostApp1
        ]
    }
}

rectangle infra #LightGrey{
    rectangle HOSTNAME_infra1 #DarkBlue[
    =HOSTNAME
    ----
    Checkpost1
]

rectangle IP_infra1 #Blue[
    =IP
    ----
    10.249.221.21
]

rectangle CPU_infra1 #Blue[
    =CPU
    ----
    8
]

rectangle RAM_infra1 #Blue[
    =RAM
    ----
    32GB
]

rectangle TYPE_infra1 #Blue[
    =TYPE
    ----
    PHYSICAL
]

rectangle VM_HYPERVISOR_infra1 #Blue[
    =VM HYPERVISER
    ----
    N/A
]

rectangle NETMASK_infra1 #Blue[
    =NETMASK
    ----
    255.255.255.128
]

rectangle OS_infra1 #Blue[
    =OS
    ----
    RHEL 8.7
]

rectangle OS_VERSION_infra1 #Blue[
    =OS VERSION
    ----
    8.7
]

rectangle KERNEL_VERSION_infra1 #Blue[
    =KERNEL VERSION
    ----
    4.15.0-46-generic
]

rectangle GATEWAY_infra1 #Blue[
    =GATEWAY
    ----
    10.249.221.1
]

rectangle LAST_PATCHED_infra1 #Blue[
    =LAST PATCHED
    ----
    22/09/23s
]
}

rectangle storage #LightGrey{
    rectangle STORAGE #DarkGoldenRod[
        =STORAGE
    ]

    rectangle NFS #GoldenRod[
    =NFS
    ----
    IP:foldername /u01/nfsstorage
]

rectangle LOCAL_DISK #GoldenRod[
    =LOCAL DISK
    ----
    sda:105GB
]

rectangle LOCAL_DISK_ATTRIBUTES #SlateGrey{
        rectangle LVM1 #GoldenRod[
    =LVM
    ----
    home
    opt
    root
    swap
    tmp
    usr
    var
    var_log_audit
    lv0
    ]

    rectangle LOCAL_DISK_PARTITION #GoldenRod[
    =LOCAL_DISK_PARTITION
    ----
    /:20GB
    /var:9GB
    /home:10GB
    /opt:6GB
    /tmp:10GB
    /boot:2GB
    /boot/efi:1GB
    ]

    rectangle VG1 #GoldenRod[
    =VG
    ----
    /dev/mapper/vg0-lv0:500GB
    ]

        rectangle PV1 #GoldenRod[
    =PV
    ----
    PV Name=/dev/sda3
    PV Size=101.00g
    PV Name=/dev/sdb
    PV Size=500.00g
    ]
}


rectangle SAN_DISK #GoldenRod[
    =SAN_DISK
    ----
    sda:sdb:500GB
]

rectangle SAN_DISK_ATTRIBUTES #SlateGrey{

    rectangle SAN_DISK_PARTITION #GoldenRod[
    =SAN_DISK_PARTITION
    ----
    /:20GB
    /var:9GB
    /home:10GB
    /opt:6GB
    /tmp:10GB
    /boot:2GB
    /boot/efi:1GB
    ]
        rectangle LVM2 #GoldenRod[
    =LVM
    ----
    home
    opt
    root
    swap
    tmp
    usr
    var
    var_log_audit
    lv0
    ]

    rectangle VG2 #GoldenRod[
    =VG
    ----
    /dev/mapper/vg0-lv0:500GB
    ]

    rectangle PV2 #GoldenRod[
    =PV
    ----
    PV Name=/dev/sda3
    PV Size=101.00g
    PV Name=/dev/sdb
    PV Size=500.00g
    ]

    rectangle WWN #GoldenRod[
    =WWN
    ----
    xyzafldsafla
    ]
}

rectangle OBJECT_STORAGE #GoldenRod[
    =OBJECT STORAGE
    ----
    https://Objectstorage.nic.com
]

    /'rectangle HOSTNAME #GoldenRod[
    =HOSTNAME
    ----
    Checkpost1]
} '/
}

Heading --[hidden]d-> NIC
' lines & formatting: https://blog.mrhaki.com/2016/12/plantuml-pleasantness-change-line-style.html#:~:text=We%20can%20choose%20the%20following,%2C%20plain%20%2C%20dotted%20and%20dashed%20.
NIC -- MyGov
NIC -[bold,#DarkRed]d--> eTransport
NIC -- NSP
eTransport -[bold,#DarkRed]--> Checkpost
eTransport --> Vahan
eTransport --> Sarathi
Checkpost-[bold,#DarkRed]--> DC_Delhi
DC_Delhi --- Pre_Production
DC_Delhi --- Testing
DC_Delhi --[bold,#DarkRed]-> Staging
DC_Delhi -- Production
Staging -[bold,#DarkGoldenRod]-- storage
Staging -[bold,#DarkBlue]-- infra
infra ---[hidden]d----> application
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''''''''''''''''''STAGING TO APPLICATION''''''''''''''''''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
Staging -[bold,#Lime]d--> App_Start
Tomcat_Details -[hidden]d--> SERVICES
Tomcat_Details -[hidden]r--> App_Details
App_Start -[bold,#Lime]d----> Services_Start
Tomcat_Start -[hidden]d--> Services_Start 
Tomcat_Details -[hidden]r- App_Details
App_Start -[bold,#Lime]d-> Tomcat_Start
Tomcat_Start -[hidden]d-> App_Details

App_Start -[bold,#Lime]d---> Network_Start
App_Details -[hidden]d---> Network_Start
App_Details -[hidden]d---> Database_Start
network_details <-[hidden]l- Database_Start
App_Start -[bold,#Lime]d-> Database_Start
''db
Database_Start -[bold,#Lime]d-> BACKUP
BACKUP -[bold,#Lime]d-> BACKUP_CONFIG
BACKUP -[bold,#Lime]d-> LAST_BACKUP_DATE
Database_Start -[bold,#Lime]d-> DATABASE_apps1
DATABASE_apps1 -[bold,#Lime]d-> DB_SERVER_READ_apps1
DATABASE_apps1 -[bold,#Lime]d-> DB_SERVER_WRITE_apps1
''services
Services_Start -[bold,#Lime]d-> SERVICE_NAME_apps1
Services_Start -[bold,#Lime]d-> SERVICE_PATH_apps1
LISTENING_IP_apps1 -[hidden]d-> SERVICE_PATH_apps1
LISTENING_PORT_apps1 -[hidden]d-> SERVICE_NAME_apps1
Services_Start -[bold,#Lime]d-> LISTENING_IP_apps1
Services_Start -[bold,#Lime]d-> LISTENING_PORT_apps1
''tomcat
Tomcat_Start -[bold,#Lime]d-> TOMCAT_NAME_apps1
Tomcat_Start -[bold,#Lime]d-> WAR_DEPLOYED_apps1
Tomcat_Start -[bold,#Lime]d-> TOMCAT_PORT_apps1
TOMCAT_NAME_apps1 -[hidden]d-> TOMCAT_PORT_apps1
Tomcat_Start -[bold,#Lime]d-> WEBAPP_PATH_apps1
Tomcat_Start -[bold,#Lime]d-> LOGS_PATH_apps1
LOGS_PATH_apps1 -[hidden]d-> CONFIG_MAP_apps1
Tomcat_Start -[bold,#Lime]d-> CONFIG_MAP_apps1
''network
'Network_Start -[bold,#Lime]d-> IP
Network_Start -[bold,#Lime]d-> LB_IP
'IP -[hidden]d-> LB_IP
Network_Start -[bold,#Lime]d-> MAC_IP
Network_Start -[bold,#Lime]d-> HAPROXY_PORT
MAC_IP -[hidden]d-> HAPROXY_PORT
Network_Start -[bold,#Lime]d-> NTP_SERVER_apps1
''Apps
APP_NAME -[hidden]d-> PUBLIC_URL
LAST_APP_VERSION -[hidden]d-> PUBLIC_URL 
API_Webservice_apps1 -[hidden]d--> APP_DEPLOYMENT_PREREQUISITES_apps1 
GIT_REPOSITORY_LINK -[hidden]d-> OWNER_CONTACT 

'APP_NAME -[bold,#Lime]d-> HOSTNAME_apps1
App_Start -[bold,#Lime]d-> APP_NAME
App_Start -[bold,#Lime]d-> APP_DESCRIPTION
App_Start -[bold,#Lime]d-> PUBLIC_URL
App_Start -[bold,#Lime]d-> LAST_APP_VERSION
App_Start -[bold,#Lime]d-> OWNER_CONTACT
App_Start -[bold,#Lime]d--> APP_DEPLOYMENT_PREREQUISITES_apps1
App_Start -[bold,#Lime]d-> API_Webservice_apps1
App_Start -[bold,#Lime]d-> APP_PLATFORM
App_Start -[bold,#Lime]d-> PROGRAMMING_LANGUAGE
PROGRAMMING_LANGUAGE -[bold,#Lime]d-> PROGRAMMING_LANGUAGE_VERSION
App_Start -[bold,#Lime]d-> GIT
GIT -[bold,#Lime]d-> GIT_REPOSITORY_LINK
App_Start -[bold,#Lime]d-> DEPLOYMENT_DOCUMENT
DEPLOYMENT_DOCUMENT -[bold,#Lime]d-> DOCUMENT_PATH
DEPLOYMENT_DOCUMENT -[bold,#Lime]d-> DOCUMENT_TYPE_apps1

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''''''''''''''''''STAGING TO INFRA''''''''''''''''''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
infra --[bold,#DarkBlue]-> HOSTNAME_infra1
HOSTNAME_infra1 -[bold,#DarkBlue]-> IP_infra1
HOSTNAME_infra1 -[bold,#DarkBlue]-> CPU_infra1
HOSTNAME_infra1 -[bold,#DarkBlue]-> RAM_infra1
HOSTNAME_infra1 -[bold,#DarkBlue]-> TYPE_infra1
HOSTNAME_infra1 -[bold,#DarkBlue]-> VM_HYPERVISOR_infra1
HOSTNAME_infra1 -[bold,#DarkBlue]-> NETMASK_infra1
HOSTNAME_infra1 -[bold,#DarkBlue]-> OS_infra1
OS_infra1 -[bold,#DarkBlue]d-> OS_VERSION_infra1
HOSTNAME_infra1 -[bold,#DarkBlue]-> KERNEL_VERSION_infra1
HOSTNAME_infra1 -[bold,#DarkBlue]-> GATEWAY_infra1
HOSTNAME_infra1 -[bold,#DarkBlue]-> LAST_PATCHED_infra1

'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
'''''''''''''''''''STAGING TO STORAGE''''''''''''''''''
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
storage -[bold,#DarkGoldenRod]-> STORAGE
STORAGE -[bold,#DarkGoldenRod]-> NFS
STORAGE -[bold,#DarkGoldenRod]-> LOCAL_DISK
LOCAL_DISK -[bold,#DarkGoldenRod]d--> LOCAL_DISK_ATTRIBUTES
LOCAL_DISK -[hidden]d-> LOCAL_DISK_ATTRIBUTES
PV1 -[bold,#GoldenRod]r-> VG1
VG1 -[bold,#GoldenRod]r-> LOCAL_DISK_PARTITION
LOCAL_DISK_PARTITION =[bold,#GoldenRod]r-> LVM1
STORAGE -[bold,#DarkGoldenRod]-> OBJECT_STORAGE
STORAGE -[bold,#DarkGoldenRod]-> SAN_DISK
SAN_DISK -[bold,#DarkGoldenRod]d--> SAN_DISK_ATTRIBUTES
WWN -[bold,#GoldenRod]r-> PV2
PV2 -[bold,#GoldenRod]r-> VG2
VG2 -[bold,#GoldenRod]r-> SAN_DISK_PARTITION
SAN_DISK_PARTITION -[bold,#GoldenRod]r-> LVM2

@enduml
